### ISSUE TITLE
Invalid JavaScript

### ISSUE THREAD

**Issue by StampixSMO** [CleverTap/clevertap-node#11]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `clevertap@1.2.0` for the project I'm working on.

**Details**

There's a missing variable declaration (or a misplaced semicolon, should be a comma). This fails in more recent JS versions since it's not actual valid JS.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/clevertap/lib/clevertap-api.js b/node_modules/clevertap/lib/clevertap-api.js
index 4d16bfd..48d5794 100644
--- a/node_modules/clevertap/lib/clevertap-api.js
+++ b/node_modules/clevertap/lib/clevertap-api.js
@@ -3,7 +3,7 @@ const request       = require('request');
 const querystring   = require('querystring');
 
 const API_HOSTNAME  = "api.clevertap.com";
-      API_VERSION   = 1;
+const API_VERSION   = 1;
 
 const CREATE = "create",
       ESTIMATE = "estimate",
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by StampixSMO** [comment]
FYI the same is true for a variable named `recordType`..

**Comment by KambleSonam** [comment]
Hello @StampixSMO, Thank you for pointing it out. We will fix the code and release it by next week.

**Comment by KambleSonam** [comment]
@StampixSMO New package is released with these fixes. Thank You. Closing this issue
