### ISSUE TITLE
Can't install with yarn on recent node versions

### ISSUE THREAD

**Issue by recidive** [CleverTap/clevertap-node#3]
Hello, when can we expect a new version published in NPM?

It's been a while since the problem was fixed but no release was published since:

https://github.com/CleverTap/clevertap-node/issues/1

yarn add clevertap
yarn add v1.17.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error clevertap@1.1.0: The engine "node" is incompatible with this module. Expected version "4.2.3". Got "12.10.0"
error Found incompatible module.

Can you publish a new version ASAP?

**Comment by fskinner** [comment]
I'm also having this issue.

**Comment by Jonovono** [comment]
Same issue, any updates?

**Comment by HammzaHM** [comment]
The same issue here, any help please

**Comment by HammzaHM** [comment]
@prashantpandey10 can you please help us out ???

**Comment by royson-ct** [comment]
We've published the new version on npm. Yarn install will work now.
