### ISSUE TITLE
The request package has been deprecated

### ISSUE THREAD

**Issue by dakshshah96** [CleverTap/clevertap-node#8]
As of Feb 11th 2020, request is fully deprecated. No new changes are expected to land. More info here: https://github.com/request/request/issues/3142.

It's been 2+ yrs, and the `clevertap-node` package should no longer be using `request`.

[axios](https://www.npmjs.com/package/axios) would be a good alternative.

**Comment by ikonicity-airban** [comment]
but `Axios` is not built-in right

**Comment by dakshshah96** [comment]
@Ikonicity-Airban `request` is not built-in too. Here is the package: https://github.com/request/request

**Comment by ikonicity-airban** [comment]
> @Ikonicity-Airban `request` is not built-in too. Here is the package: https://github.com/request/request

@dakshshah96 
that was a rhetorical question though, but thanks anyways

**Comment by KambleSonam** [comment]
'request' package is replaced with 'node-fetch' package.
