### ISSUE TITLE
#DEPRECATED REQUEST PACKAGE

### ISSUE THREAD

**Issue by ikonicity-airban** [CleverTap/clevertap-node#9]
A quick question, please what about those packages that use this `request module` how do we bypass the deprecation warnings cause this message always popup up when I  am installing firebase across devices.
`npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142`

**Comment by KambleSonam** [comment]
'request' package is replaced with 'node-fetch' package.
